server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hopital?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true